=== pierodbspl/practica-git-2/Tema 4/Actores/Actores.dtd
<!ELEMENT Cine (Peliculas, Actores, Directores)>
<!ELEMENT Peliculas (Pelicula+)>
<!ELEMENT Pelicula (Nombre, FechaEstreno)>
<!ELEMENT Actores (Actor+)>
<!ELEMENT Actor (Nombre, Sexo, FechaNacimiento, PaginaWeb, PeliculasHechas)>
<!ELEMENT Directores (Director+)>
<!ELEMENT Director (Nombre, Sexo, FechaNacimiento, PaginaWeb, PeliculasHechas)>

<!ATTLIST Pelicula id ID #IMPLIED>
<!ATTLIST Pelicula director IDREF #REQUIRED>
<!ATTLIST Pelicula actor IDREFS #REQUIRED>
<!ATTLIST Actor id ID #REQUIRED>
<!ATTLIST Director id ID #REQUIRED>
<!ATTLIST PeliculasHechas id IDREFS #IMPLIED>


<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Sexo (#PCDATA)>
<!ELEMENT FechaEstreno (#PCDATA)>
<!ELEMENT FechaNacimiento (#PCDATA)>
<!ELEMENT PaginaWeb (#PCDATA)>
<!ELEMENT PeliculasHechas EMPTY>




<!-- 
ELEMENTOS:
niguno -> Uno obligatorio y solo puede ser uno
? -> Opcionales
* -> 0 o varios
+ -> 1 o varios
, -> Indica secuencia, el orden importa
| -> contenido alternativo

TIPO DE ELEMENTOS:
#PCDATA -> Datos
EMPTY -> Elementos vacíos

TIPO DE ATRIBUTOS:
IDREF -> Referencia un ID
IDREFS -> Referencia uno o más IDs

VALOR DEL ATRIBUTO:
#REQUIRED -> Valor obligatorio
#IMPLIED -> Opcional
-->

=== pierodbspl/practica-git-2/Tema 4/Actores/Actores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Cine SYSTEM "Actores.dtd">

<Cine>

    <Peliculas>

        <Pelicula id="p1" director="D12" actor="A12">
            <Nombre>El Quinto Elemento</Nombre>
            <FechaEstreno>03/04/1997</FechaEstreno>
        </Pelicula>

        <Pelicula id="p2" director="D52" actor="A52">
            <Nombre>El Diablo Meti√≥ la Mano</Nombre>
            <FechaEstreno>12/08/1998</FechaEstreno>
        </Pelicula>

        <Pelicula id="p3" director="D15" actor="A52">
            <Nombre>La Milla Verde</Nombre>
            <FechaEstreno>02/04/2000</FechaEstreno>
        </Pelicula>

        <Pelicula id="p4" director="D12" actor="A54">
            <Nombre>Ali-G Anda Suelto</Nombre>
            <FechaEstreno>25/05/2002</FechaEstreno>
        </Pelicula>

    </Peliculas>

    <Actores>

        <Actor id="A51">
            <Nombre>Tom Hanks</Nombre>
            <Sexo>Mujer</Sexo>
            <FechaNacimiento>09/07/1956</FechaNacimiento>
            <PaginaWeb></PaginaWeb>
            <PeliculasHechas/>
        </Actor>

        <Actor id="A52">
            <Nombre >Devon Sawa</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1986</FechaNacimiento>
            <PaginaWeb>www.devonsito.com</PaginaWeb>
            <PeliculasHechas id="p2"/>
        </Actor>

        <Actor id="A54">
            <Nombre >Sacha Baron Cohen</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1979</FechaNacimiento>
            <PaginaWeb>www.wsmith.com</PaginaWeb>
            <PeliculasHechas id="p4"/>
        </Actor>

        <Actor id="A12">
            <Nombre >Gary Oldman</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1963</FechaNacimiento>
            <PaginaWeb>www.garyfukingamo.com</PaginaWeb>
            <PeliculasHechas id="p1"/>
        </Actor>

    </Actores>

    <Directores>
        
        <Director id="D52">
            <Nombre>Rodman Flender</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1978</FechaNacimiento>
            <PaginaWeb>www.superdirector52.com</PaginaWeb>
            <PeliculasHechas/>
        </Director>

        <Director id="D12">
            <Nombre>Luc Besson</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1963</FechaNacimiento>
            <PaginaWeb>www.superdirector12.com</PaginaWeb>
            <PeliculasHechas/>
        </Director>

        <Director id="D15">
            <Nombre>Frank Darabont</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1947</FechaNacimiento>
            <PaginaWeb>www.superdirector12.com</PaginaWeb>
            <PeliculasHechas/>
        </Director>

        <Director id="D31">
            <Nombre>Mark Mylod</Nombre>
            <Sexo>Hombre</Sexo>
            <FechaNacimiento>31/12/1947</FechaNacimiento>
            <PaginaWeb>www.superdirector12.com</PaginaWeb>
            <PeliculasHechas/>
        </Director>
    
    </Directores>
</Cine>
